export const GET_ORIGINAL_QUESTIONS = "GET_ORIGINAL_QUESTIONS";
export const POST_NEW_QUESTION = "POST_NEW_QUESTION";
export const POST_NEW_OFFER = "POST_NEW_OFFER";
export const GET_OFFERS = "GET_OFFERS";
