export const GET_ORIGINAL_QUESTIONS = "GET_ORIGINAL_QUESTIONS";
export const POST_NEW_QUESTION = "POST_NEW_QUESTION";
export const POST_NEW_OFFER = 'POST_NEW_OFFER';
export const GET_OFFERS_COMPANY = 'GET_OFFERS_COMPANY';
export const GET_COMPANY_INFO = 'GET_COMPANY_INFO';
export const GET_OFFERS = 'GET_OFFERS';
export const FETCH_CITIES = 'FETCH_CITIES';
export const GET_ID_COMPANY = 'GET_ID_COMPANY';
